Specify Delta t in waveform shifting method
heroxbd/waveform-analysis pull request #137
Opened 2022-04-26 14:39 UTC by littlewu2508

2022-04-26 15:35 UTC, heroxbd requested changes

2022-04-26 15:35 UTC, heroxbd commented on Note/Algorithm.tex
> +  \label{eq:waveform-shift-alpha}
RSS 在前面已经有定义了，不必重新写出积分定义式。

2022-04-26 15:35 UTC, heroxbd commented on Note/Algorithm.tex
> +\textit{Peak finding} is more effective than waveform shifting by exploiting PE pulses.  We smooth the waveforms by a low-pass Savitzky-Golay filter~\cite{savitzky_smoothing_1964} and find all the pe
使用 eqref

2022-04-26 15:46 UTC, heroxbd requested changes

2022-04-26 15:46 UTC, heroxbd commented on Note/Algorithm.tex
> +\textit{Peak finding} is more effective than waveform shifting by exploiting PE pulses.  We smooth the waveforms by a low-pass Savitzky-Golay filter~\cite{savitzky_smoothing_1964} and find all the pe
这个式子太拥挤了，还是放在 equation 环境里。或者只保留 `\arg\underset{t}{\max} V_\mathrm{PE}(t)`

2022-04-26 15:46 UTC, heroxbd commented on Note/Algorithm.tex
> +    & \Delta t \text{ satisfies } \int_{0}^{\Delta t} V_\mathrm{PE}(t) \mathrm{d}t = \frac{1}{2} \int_{0}^{\infty} V_\mathrm{PE}(t) \mathrm{d}.
少一个 t

2022-04-26 15:46 UTC, heroxbd commented on Note/Algorithm.tex
> +    & \Delta t \equiv \arg\underset{\Delta t}{\min} D_\mathrm{w}\left[ V_\mathrm{PE}(t), \delta(t-\Delta t) \right] \\
定义用的 `\Delta t` 和式子中的 `\Delta t` 重复不好。换一个字母。

2022-04-26 15:46 UTC, heroxbd commented on Note/Algorithm.tex
> +  \label{eq:waveform-shift-alpha}
与 `\Delta t` 同理，`\alpha` 前后不应重复，等号左边可以写 `\hat{\alpha}`。

2022-04-26 15:46 UTC, heroxbd commented on Note/Algorithm.tex
> +Though the obtained $\hat{q}_i = \alpha w(t_i)$  are smaller than PE charges as in figure~\ref{fig:shifting}, waveform shifting does minimal analysis and serves as a baseline method.
`$\hat{q}_i = \alpha w(t_i)$` 就在上面，不必重复。为什么 `\hat{q}_i` 比 PE charges 小？

2022-04-26 15:46 UTC, heroxbd commented on Note/Algorithm.tex
> +\textit{Peak finding} is more effective than waveform shifting by exploiting PE pulses.  We smooth the waveforms by a low-pass Savitzky-Golay filter~\cite{savitzky_smoothing_1964} and find all the pe
`$i \in \{\text{peak index}\}$` 这个集合符号看起来并没有简化论证，还不如直接写 except one $i$ correspond to a peak.

2022-04-27 03:10 UTC, littlewu2508 commented on Note/Algorithm.tex
> +  \label{eq:waveform-shift-alpha}
Done. 哑元统一用了 \alpha', \Delta t'.

2022-04-27 03:18 UTC, littlewu2508 commented on Note/Algorithm.tex
> +\textit{Peak finding} is more effective than waveform shifting by exploiting PE pulses.  We smooth the waveforms by a low-pass Savitzky-Golay filter~\cite{savitzky_smoothing_1964} and find all the pe
Done.

把 Algorithm.tex 里所有 equation 的 \ref 都换成 \eqref 了

放进了 equation

引用 RSS 不需要指明 i 了

2022-04-27 03:18 UTC, littlewu2508 commented on Note/Algorithm.tex
> +    & \Delta t \equiv \arg\underset{\Delta t}{\min} D_\mathrm{w}\left[ V_\mathrm{PE}(t), \delta(t-\Delta t) \right] \\
Done

2022-04-27 03:20 UTC, littlewu2508 commented on Note/Algorithm.tex
> +Though the obtained $\hat{q}_i = \alpha w(t_i)$  are smaller than PE charges as in figure~\ref{fig:shifting}, waveform shifting does minimal analysis and serves as a baseline method.
Done.

2022-04-27 11:36 UTC, closed without merging